var found = true;
var grade = 88.6;
var firstName = "Anup";
var lastName = 'Kumar';
found = 0;
grade = "A";
firstName = 1;
console.log(found);
console.log("The grade is " + grade);
console.log("Hi ".concat(firstName, " ").concat(lastName));
